### ISSUE TITLE
Fayldan oxuma

### ISSUE THREAD

**Issue by sakitA** [Gunay-Jafar/CBAR_Currency#1]
Mərkəzi bankın səhifəsindən günlük məzənnə məlumatlarını bir faylda saxlayın. Daha sonra terminaldan istifadəçinin daxil etdiyi ölkə koduna görə məzənnə məlumatlarını ekrana çap etmək.

**Tapşrığın icrası üçün gərəkli mövzular**
- [x] - XMLin fayldan oxunması
- [x] - proqramın terminal vasitəsi ilə istadəçi ilə integrasiyası(istifadəçinin girişləri əsasında komandaların icrası)
- [x] - proqram istifadəçi proqramı sonlandırına qədər hər dəfə istifadəçidən sorğu qəbul etməlidir
- [x] - əgər istifadəçi ESC düyməsini basarsa bu zoman proqram sonlanmalıdır 

**QEYD**: hər hansı bir sual və yaxud çətinlik olarsa buradan `comment` vasitəsi ilə yaza bilərsiniz

**Comment by sakitA** [comment]
bu vaxta qədər işləmisənsə qısa vaxt sonra komandaya rahat qoşula bilərsən 👍

**Comment by Gunay-Jafar** [comment]
Cox sagolun inshAllah elimden geleni edecem)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

3 sen 2020, C.a. tarixində 23:13 tarixində Sakit <notifications@github.com>
yazdı:
